# See https://pre-commit.com for documentation
# See https://pre-commit.com/hooks.html for available hooks and their repos

# Configure which hooks to run with "repository mappings". These identify a repo
# by its revision or tag and then list out the hooks to run from that repository
# using "hook mappings".
# The code that these hooks run can be found in their repo in a top-level
# pre_commit_hooks folder or in a .pre-commit-hooks.yaml file that points to the
# executable to run.
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # latest tag as of Nov 5, 2023
    hooks:
    -   id: debug-statements
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0 # latest tag as of Nov 5, 2023
    hooks:
    -   id: isort
        args: ["--check", "--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 23.10.1 # latest tag as of Nov 5, 2023
    hooks:
    -   id: black
        args: ["--check"]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0 # latest tag as of Nov 5, 2023
    hooks:
    -   id: flake8
        additional_dependencies: [mccabe]
        args: ["--max-complexity", "10"]
# TODO: Getting errors about imports because virtual environment of pre-commit
# does not install package dependencies
# -   repo: https://github.com/PyCQA/pylint
#     rev: v3.0.1 # latest tag as of Nov 5, 2023
#     hooks:
#     -   id: pylint
#         args: ["--rcfile", "pyproject.toml"]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.6.1 # latest tag as of Nov 5, 2023
#     hooks:
#     -   id: mypy
