[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lexpkg"

[tools.pylint.main]
init-hook = "from pylint.config import find_pylintrc; import os, sys; sys.path.append(os.path.dirname(find_pylintrc()))"
